---
- hosts: all
  tasks:
  - name: Create stack user
    user: name=stack
    sudo: yes

  - name: Add stack user to the sudoers
    copy:
      dest: "/etc/sudoers.d/stack"
      content: "stack  ALL=(root)  NOPASSWD: ALL"
      mode: 0440

  - name: Create stack user and set authorized key
    authorized_key:
      user: stack
      state: present
      key: "{{ lookup('file', 'key_osp.pub') }}"

  - name: Debug msg
    copy:
      dest: "/etc/nadeem"
      content: "{{ NODE_IP }}"
