---
- name: Play book to configure and deploy overcloud services 
  hosts: all
 
  tasks:
  - name: Ansible check template directory exists.
    stat:
     path: /home/stack/templates/
    register: my_folder

  - name: "echo if directory already existed"
    debug:
      msg: "Template directory is already existed"
    when: my_folder.stat.exists
 
  - name: "Ansible Create directory if not exists"
    copy:
      src: templates
      dest: /home/stack/
    when: my_folder.stat.exists == false
 

  - name: Ansible check if deployment script exists.
    stat:
     path: /home/stack/overcloud_deploy.sh
    register: my_file

  - name: Copy deployment script
    shell: 'cp  /home/stack/templates/overcloud_deploy.sh  /home/stack/. ; chmod 777 /home/stack/overcloud_deploy.sh'
    when: my_file.stat.exists == false

  - block:
        - name: Execute Overcloud Deployment
          shell: ./overcloud_deploy.sh
          args:
            chdir: /home/stack/
          register: execution_status

    rescue:
        - debug:
            msg: "{{ execution_status }}"
