parameter_defaults:
    PublicVirtualFixedIPs: [{'ip_address':'10.8.59.1'}]
    ControlPlaneDefaultRoute: 192.168.24.1
    ControlPlaneSubnetCidr: '24'
    DnsServers:
    - 10.11.5.19
    EC2MetadataIp: 192.168.24.1
    ExternalAllocationPools:
    -   end: 10.8.59.5
        start: 10.8.59.1
    ExternalInterfaceDefaultRoute: 10.8.59.254
    ExternalNetCidr: 10.8.58.0/23
    InternalApiAllocationPools:
    -   end: 10.9.108.199
        start: 10.9.108.1
    InternalApiNetCidr: 10.9.108.0/24
    InternalApiNetworkVlanID: 260
    NeutronBridgeMappings: datacentre:br-ex,tenant:br-isolated
    NeutronEnableIsolatedMetadata: true
    NeutronExternalNetworkBridge: ''
    NeutronNetworkType: vxlan
    NeutronNetworkVLANRanges: tenant:1000:2000
    NeutronTunnelTypes: vxlan
    StorageAllocationPools:
    -   end: 10.9.106.199
        start: 10.9.106.1
    StorageMgmtAllocationPools:
    -   end: 10.9.107.199
        start: 10.9.107.1
    StorageMgmtNetCidr: 10.9.107.0/24
    StorageMgmtNetworkVlanID: 259
    StorageNetCidr: 10.9.106.0/24
    StorageNetworkVlanID: 258
    TenantAllocationPools:
    -   end: 10.9.109.199
        start: 10.9.109.1
    TenantNetCidr: 10.9.109.0/24
    TenantNetworkVlanID: 261
resource_registry:
    OS::TripleO::Compute::Net::SoftwareConfig: compute.yaml
    OS::TripleO::Controller::Net::SoftwareConfig: controller.yaml
